-- MySQL Script generated by MySQL Workbench
-- Thu May 11 13:07:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eg_sns
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eg_sns
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eg_sns` DEFAULT CHARACTER SET utf8 ;
USE `eg_sns` ;

-- -----------------------------------------------------
-- Table `eg_sns`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eg_sns`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `login_id` VARCHAR(32) NOT NULL COMMENT 'ログインID',
  `password` VARCHAR(32) NOT NULL COMMENT 'パスワード',
  `name` VARCHAR(32) NOT NULL COMMENT '名前',
  `email_address` VARCHAR(256) NOT NULL COMMENT 'メールアドレス',
  `icon_uri` VARCHAR(2000) NULL COMMENT 'プロフィールアイコンURI',
  `profile` TEXT NULL COMMENT 'プロフィール',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `updated` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'ユーザー';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
